#服务名
spring:
  application:
    name: lowcode-core
  #邮箱配置
  mail:
    host: 127.0.0.1
    username:
    password:
    properties: { 'mail.smtp.ssl.enable', true }
    test-connection: false
    protocol: smtps
    port: 465
  #redis配置
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      database: 0

#服务端口
server:
  port: 9001

#mybatis配置
mybatis:
  jdbc:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.4.21:33826/mars?useOldAliasMetadataBehavior=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2b8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: root
  # mybatis对应的实体类
  mapper-locations: classpath:com/**/mapper/**/*.xml
  type-aliases-package: com.**.domain

#打印sql日志
logging:
  config: classpath:logback.xml
